#!/usr/bin/env python3
"""Build the source-verified CRIRES+ literature census (RYA-1057)."""
import csv, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/audit/rya1057_crires_literature'
FIELDS=['reference','year','lane','crires_plus_confirmed','targets','codex_overlap','stellar_type','program_id','band_setup','wavelength_range','resolution','elements_isotopes','diagnostics','line_list_source','gf_provenance','hfs_isotopes','model_regime','atmosphere_code','continuum_method','telluric_method','uncertainty_model','machine_readable_lines','public_spectra','codex_action','notes','source_url']

ROWS=[
{'reference':'Elgueta et al. 2026, A&A 710 A111','year':2026,'lane':'STELLAR ABUNDANCE — PRIMARY','crires_plus_confirmed':'yes','targets':'Sun (Vesta); Procyon; eps Eri; Arcturus; beta Hyi; gamma Sge','codex_overlap':'exact: Sun|Procyon|eps Eri','stellar_type':'F/G/K dwarfs; subgiant; FGK/M giants','program_id':'','band_setup':'Y;J;H','wavelength_range':'9800-18000 A','resolution':'~100000','elements_isotopes':'atomic species in 1700-transition tables','diagnostics':'depth;saturation;EW purity;GoF;robust','line_list_source':'VALD3 selection; CDS J/A+A/710/A111','gf_provenance':'laboratory-anchored claims; per-line primary-reference trace still required','hfs_isotopes':'not established by census','model_regime':'1D LTE synthesis','atmosphere_code':'paper/CDS metadata review required','continuum_method':'published normalized spectra','telluric_method':'paper review required','uncertainty_model':'per-line fit diagnostics','machine_readable_lines':'yes; already vendored data/reference/elgueta2026_vizier','public_spectra':'yes; 18 normalized spectra in CDS','codex_action':'transition-identity cross-match; same-target validation; Fe/Al/CNO deltas','notes':'323 Y + 292 J + 1085 H; never promote from wavelength alone','source_url':'https://cdsarc.cds.unistra.fr/viz-bin/ReadMe/J/A%2BA/710/A111?format=html&tex=true'},
{'reference':'Chiappino et al. 2026, ApJ 1006 32','year':2026,'lane':'STELLAR ABUNDANCE — PRIMARY','crires_plus_confirmed':'yes','targets':'30 Liller 1 RGB stars','codex_overlap':'none','stellar_type':'RGB','program_id':'BulCO Large Program','band_setup':'J1226;H1582;K2166','wavelength_range':'J/H/K settings','resolution':'~50000','elements_isotopes':'Fe;C;N;O;Na;Mg;Al;Si;S;Ca;Sc;Ti;V;Cr;Co;Ni;Cu;Zn;Y;Nd;12C/13C','diagnostics':'atomic;CO;OH;CN','line_list_source':'VALD3 atomic; molecular CO/OH/CN','gf_provenance':'VALD3 distributor only; authoritative sources untraced','hfs_isotopes':'HFS included for odd elements; 12C/13C','model_regime':'1D LTE','atmosphere_code':'MARCS; TURBOSPECTRUM','continuum_method':'continuum contribution reported ~1-2%','telluric_method':'paper review required','uncertainty_model':'random and parameter terms','machine_readable_lines':'reported yes; acquisition pending','public_spectra':'ESO archive query pending','codex_action':'acquire line list; CNO/Fe/Al/element deltas; do not calibrate to bulge abundances','notes':'Source verified via arXiv 2606.11329','source_url':'https://arxiv.org/abs/2606.11329'},
{'reference':'ESO CRIRES+ Science Verification 107.22SQ','year':2021,'lane':'STELLAR ABUNDANCE — PRIMARY','crires_plus_confirmed':'yes','targets':'Nuclear Star Cluster crowded/extincted fields','codex_overlap':'none','stellar_type':'late-type stars (target list pending archive resolution)','program_id':'107.22SQ','band_setup':'archive query pending','wavelength_range':'archive query pending','resolution':'40000/80000 configuration-dependent','elements_isotopes':'program intent: stellar abundances','diagnostics':'pending publication/archive linkage','line_list_source':'unknown','gf_provenance':'unknown','hfs_isotopes':'unknown','model_regime':'unknown','atmosphere_code':'unknown','continuum_method':'unknown','telluric_method':'nightly telluric standards per ESO SV','uncertainty_model':'unknown','machine_readable_lines':'no publication identified','public_spectra':'SV data public','codex_action':'resolve archive datasets and resulting publications','notes':'Partially completed; program is evidence, not an abundance result','source_url':'https://www.eso.org/sci/activities/vltsv/criresplussv.html'},
{'reference':'ESO CRIRES+ Science Verification 107.22SZ','year':2021,'lane':'STELLAR ABUNDANCE — PRIMARY','crires_plus_confirmed':'yes','targets':'HD 222925','codex_overlap':'none','stellar_type':'metal-poor r-process-enhanced star','program_id':'107.22SZ','band_setup':'archive query pending','wavelength_range':'NIR','resolution':'40000/80000 configuration-dependent','elements_isotopes':'rare/heavy elements (program intent)','diagnostics':'pending publication linkage','line_list_source':'unknown','gf_provenance':'unknown','hfs_isotopes':'required; status unknown','model_regime':'unknown','atmosphere_code':'unknown','continuum_method':'unknown','telluric_method':'nightly telluric standards per ESO SV','uncertainty_model':'unknown','machine_readable_lines':'unknown','public_spectra':'SV data public','codex_action':'resolve dataset/publications and heavy-element lines','notes':'Completed program; not yet evidence of a published abundance product','source_url':'https://www.eso.org/sci/activities/vltsv/criresplussv.html'},
{'reference':'Codex-target CRIRES+ observation leads (ticket-verified queue)','year':2026,'lane':'PLANET/ATMOSPHERE','crires_plus_confirmed':'yes','targets':'55 Cnc; HD 209458; WASP-107','codex_overlap':'system-host: 55 Cnc A|HD 209458|WASP-107','stellar_type':'planet hosts','program_id':'publication/archive resolution pending','band_setup':'55 Cnc K2148; HD 209458 H; WASP-107 pending','wavelength_range':'setting-specific','resolution':'CRIRES+ high resolution','elements_isotopes':'planetary molecules only','diagnostics':'stellar removal/template handling','line_list_source':'publication-specific','gf_provenance':'not stellar-gf authority','hfs_isotopes':'n/a','model_regime':'planet atmosphere retrieval/cross-correlation','atmosphere_code':'publication-specific','continuum_method':'publication-specific','telluric_method':'publication-specific','uncertainty_model':'publication-specific','machine_readable_lines':'no','public_spectra':'ESO archive query required','codex_action':'split into individual verified publications; inspect host-star holdings','notes':'Discovery queue only; never mix planetary with stellar abundances','source_url':'https://linear.app/ryans-adventure-zone/issue/RYA-1057'},
{'reference':'Ryde et al. 2009, A&A 496 701','year':2009,'lane':'LEGACY CRIRES — HISTORICAL','crires_plus_confirmed':'no (pre-upgrade CRIRES)','targets':'3 Baade window bulge giants','codex_overlap':'none','stellar_type':'giants','program_id':'60.A-9058(A)','band_setup':'H','wavelength_range':'near 1.55 um','resolution':'high resolution legacy CRIRES','elements_isotopes':'C;N;O;Ti;Fe;Si','diagnostics':'CO;CN;OH;atomic','line_list_source':'paper-specific','gf_provenance':'historical review only','hfs_isotopes':'paper review required','model_regime':'1D LTE','atmosphere_code':'MARCS; spectrum synthesis','continuum_method':'paper review required','telluric_method':'paper review required','uncertainty_model':'stellar-parameter sensitivities; <0.20 dex stated','machine_readable_lines':'unknown','public_spectra':'ESO legacy archive','codex_action':'historical CNO line-method comparison only','notes':'Explicitly segregated; never label CRIRES+','source_url':'https://doi.org/10.1051/0004-6361/200811070'}]

def write(name, fields, rows):
 OUT.mkdir(parents=True,exist_ok=True)
 with (OUT/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)

def main():
 write('publication_program_census.csv',FIELDS,ROWS)
 overlaps=[]
 for r in ROWS:
  if r['codex_overlap']!='none':
   overlaps.append({'reference':r['reference'],'lane':r['lane'],'targets':r['targets'],'overlap':r['codex_overlap'],'action':r['codex_action']})
 write('codex_target_overlap.csv',list(overlaps[0]),overlaps)
 reverse=[]
 for r in ROWS:
  if r['lane']!='STELLAR ABUNDANCE — PRIMARY': continue
  for el in [x for x in r['elements_isotopes'].split(';') if x and x not in ('atomic species in 1700-transition tables','program intent: stellar abundances','rare/heavy elements (program intent)')]:
   reverse.append({'element':el,'source':r['reference'],'settings':r['band_setup'],'same_target_evidence':r['codex_overlap'],'published_gf_source':r['gf_provenance'],'authoritative_gf_traced':'no','candidate_delta':'pending transition-level match','action_ticket':'RYA-1056/RYA-709/RYA-946'})
 write('per_element_reverse_index.csv',list(reverse[0]),reverse)
 (OUT/'summary.json').write_text(json.dumps({'rows':len(ROWS),'primary':sum(r['lane'].endswith('PRIMARY') for r in ROWS),'supporting':sum('SUPPORTING' in r['lane'] for r in ROWS),'planet':sum(r['lane']=='PLANET/ATMOSPHERE' for r in ROWS),'legacy':sum(r['lane'].startswith('LEGACY') for r in ROWS),'status':'seed census; publication/archive expansion remains open'},indent=2)+'\n')
if __name__=='__main__': main()
